# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0003_auto_20170526_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='secret',
        ),
        migrations.AddField(
            model_name='secret',
            name='like',
            field=models.ManyToManyField(related_name='liked_posts', to='dojo_secrets.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
