# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0004_auto_20170528_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='like',
            field=models.ManyToManyField(related_name='liked_secret', to='dojo_secrets.User'),
        ),
    ]
