# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets', '0005_auto_20170529_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='like',
            new_name='likes',
        ),
    ]
